### ISSUE TITLE
Does it work with MySQL?

### ISSUE THREAD

**Issue by jatoledo** [mchaloupka/EVI-SampleServer#1]
Does it work with MySQL?. 
Could you provide the configuration if the answer is yes?

**Comment by mchaloupka** [comment]
MySQL syntax is currently not supported. Can you please clarify your use case? I have not seen demand for MySQL so I am trying to understand what are the use case that could be unblocked.

**Comment by jatoledo** [comment]
It was a particular case for me.  I close this issue, thanks anyway.
